### ISSUE TITLE
Plugin breaking during game and becoming unresponsive.

### ISSUE THREAD

**Issue by keywok** [rtaylor4444/UltimateVolcanicMine#7]
During the game the plugin overlays vanished and I was unable to restore functionality. The following were the error's found within the client log:

![RuneLite_28-03-23_15-02-18](https://user-images.githubusercontent.com/71525889/228265183-1324707c-ef67-4f03-9f93-0ce7e2bb2e98.png)
![RuneLite_28-03-23_15-00-48](https://user-images.githubusercontent.com/71525889/228265185-e53a692e-b1d8-4610-94ca-35fd8f6abc1f.png)
![image](https://user-images.githubusercontent.com/71525889/228266056-2aee6612-3a76-4e84-9060-627780810421.png)

```
2023-03-28 14:14:45 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at com.ultimatevm.UltimateVolcanicMinePlugin.isInVM(UltimateVolcanicMinePlugin.java:326)
	at com.ultimatevm.UltimateVolcanicMinePlugin.onGameStateChanged(UltimateVolcanicMinePlugin.java:129)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:189)
	at client.ie(client.java:19224)
	at at.ga(at.java:1236)
	at lv.aq(lv.java:1115)
	at client.bp(client.java:1100)
	at br.aa(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-03-28 14:15:44 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.time.Duration.compareTo(Unknown Source)
	at com.volcanicmine.VMPlugin.onGameTick(VMPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:207)
	at client.ip(client.java:12917)
	at client.bp(client.java)
	at br.aa(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-03-28 14:22:23 [OkHttp https://api.runelite.net/...] INFO  net.runelite.client.party.WSClient - Websocket okhttp3.internal.ws.RealWebSocket@38850a41 opened
2023-03-28 14:26:16 [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-03-28 14:26:16 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.time.Duration.compareTo(Unknown Source)
	at com.volcanicmine.VMPlugin.onGameTick(VMPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:207)
	at client.ip(client.java:12917)
	at client.bp(client.java)
	at br.aa(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-03-28 14:36:48 [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-03-28 14:36:48 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.time.Duration.compareTo(Unknown Source)
	at com.volcanicmine.VMPlugin.onGameTick(VMPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:207)
	at client.ip(client.java:12917)
	at client.bp(client.java)
	at br.aa(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-03-28 14:47:20 [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-03-28 14:47:20 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.time.Duration.compareTo(Unknown Source)
	at com.volcanicmine.VMPlugin.onGameTick(VMPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:207)
	at client.ip(client.java:12917)
	at client.bp(client.java)
	at br.aa(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-03-28 14:57:52 [Client] WARN  n.runelite.client.eventbus.EventBus - following log message logged 1000 times!
2023-03-28 14:57:52 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.NullPointerException: null
	at java.base/java.time.Duration.compareTo(Unknown Source)
	at com.volcanicmine.VMPlugin.onGameTick(VMPlugin.java:174)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.tick(Hooks.java:207)
	at client.ip(client.java:12917)
	at client.bp(client.java)
	at br.aa(br.java:367)
	at br.run(br.java:346)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by rtaylor4444** [comment]
Thanks for posting this, I am currently having difficulty reproducing the issue. It could be related to this https://github.com/hippipi/volcanic-mine-plugin/issues/1 but I doubt it. I do take crashes like this seriously so I will be reaching out for help regarding this.

In the meantime you can use the update pending for for RuneLite on the master branch assuming you have your dev environment setup

**Comment by keywok** [comment]
Just had the exact same thing happen again. Only plugin installed is yours in regards to VM.

![image](https://user-images.githubusercontent.com/71525889/230994280-e9cb11ef-1233-4c36-8cee-925a67ee03e5.png)

**Comment by rtaylor4444** [comment]
I have implemented a fix for this I did run into that issue (finally). It seems to occur when you lag or dc but not enough to actually be logged out of the game. I'm not sure how the game engine treats this so I wont be able to fix this 100% but I can prevent my plugin from crashing. I will be sending a PR to RuneLite soon to update this.
